services:

  spark:

    image: bitnami/spark:3.5

    container_name: trading-spark

    ports:
      - "8080:8080"
      - "7077:7077"

    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./data:/opt/spark/data

    command: >
      /opt/bitnami/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    environment:
      SPARK_EXTRA_CLASSPATH: /opt/bitnami/spark/jars/*

    networks:
      - trading-network

  mongodb:
    image: mongo:7
    container_name: trading-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    networks:
      - trading-network

networks:
  trading-network:

volumes:
  mongo_data: