services:

  spark-master:
    build: .
    container_name: spark-master

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    ports:
      - "8080:8080"
      - "7077:7077"

    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./data:/opt/spark/data

    networks:
      - trading-network

  spark-worker:
    build: .
    container_name: spark-worker

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

    depends_on:
      - spark-master

    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./data:/opt/spark/data

    networks:
      - trading-network

  mongodb:
    image: mongo:7
    container_name: trading-mongodb

    command: ["mongod","--bind_ip_all"]

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    networks:
      - trading-network

networks:
  trading-network:

volumes:
  mongo-data: